version: '3.8'

volumes:
  backend_local_postgres_data: {}
  backend_local_postgres_data_backups: {}
  backend_local_redis_data: {}

services:
  django: &django
    build:
      context: ./backend
      dockerfile: ./compose/local/django/Dockerfile
    image: backend_local_django
    container_name: backend_local_django
    depends_on:
      - postgres
      - redis
      - mailpit
      - frontend
    volumes:
      - ./backend:/app:z
    env_file:
      - ./backend/.envs/.local/.django
      - ./backend/.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start
    working_dir: /app

  postgres:
    build:
      context: ./backend
      dockerfile: ./compose/production/postgres/Dockerfile
    image: backend_production_postgres
    container_name: backend_local_postgres
    volumes:
      - backend_local_postgres_data:/var/lib/postgresql/data
      - backend_local_postgres_data_backups:/backups
    env_file:
      - ./backend/.envs/.local/.postgres
    working_dir: /app

  mailpit:
    image: docker.io/axllent/mailpit:latest
    container_name: backend_local_mailpit
    ports:
      - "8025:8025"
    working_dir: /app

  redis:
    image: docker.io/redis:6
    container_name: backend_local_redis
    volumes:
      - backend_local_redis_data:/data
    working_dir: /app

  celeryworker:
    <<: *django
    image: backend_local_celeryworker
    container_name: backend_local_celeryworker
    depends_on:
      - redis
      - postgres
      - mailpit
    ports: []
    command: /start-celeryworker
    working_dir: /app

  celerybeat:
    <<: *django
    image: backend_local_celerybeat
    container_name: backend_local_celerybeat
    depends_on:
      - redis
      - postgres
      - mailpit
    ports: []
    command: /start-celerybeat
    working_dir: /app

  flower:
    <<: *django
    image: backend_local_flower
    container_name: backend_local_flower
    ports:
      - '5555:5555'
    command: /start-flower
    working_dir: /app

  frontend:
    build:
      context: ./frontend
      dockerfile: ./compose/local/Dockerfile
    image: frontend_local_nextjs
    container_name: frontend_local_nextjs
    volumes:
      - ./frontend:/app:z
    ports:
      - '3000:3000'
    env_file:
      - ./frontend/.envs/.local
    working_dir: /app