# Generated by Django 5.0.9 on 2024-12-14 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_role_user_branches_user_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Role code'),
        ),
    ]
